export const MAX_SUBMISSION_ATTEMPTS = 100;
export const MAX_SUBMISSION_FILES = 10;
export const MAX_SUBMISSION_FILE_SIZE_MB = 100;
export const MAX_SUBMISSION_NOTE_LENGTH = 20_000;
export const MAX_REPOSITORY_URL_LENGTH = 2_048;
