package com.uigrade.ai.domain.usecase

import com.uigrade.ai.domain.model.ClassMembership
import com.uigrade.ai.domain.model.Classroom
import com.uigrade.ai.domain.model.ClassroomStatus
import com.uigrade.ai.domain.model.User
import com.uigrade.ai.domain.model.UserRole
import com.uigrade.ai.domain.repository.AuthRepository
import com.uigrade.ai.domain.repository.ClassroomRepository
import java.time.LocalDateTime
import java.util.UUID
import javax.inject.Inject

class CreateClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(
        name: String,
        courseCode: String,
        description: String,
        semester: String
    ): Result<Classroom> {
        if (name.isBlank()) return Result.failure(IllegalArgumentException("Tên lớp không được trống"))
        if (courseCode.isBlank()) return Result.failure(IllegalArgumentException("Mã học phần không được trống"))
        if (semester.isBlank()) return Result.failure(IllegalArgumentException("Học kỳ không được trống"))

        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))

        val classroom = Classroom(
            id = UUID.randomUUID().toString(),
            name = name.trim(),
            courseCode = courseCode.trim().uppercase(),
            description = description.trim(),
            lecturerId = user.id,
            lecturerName = user.name,
            joinCode = "", // Generated by repository
            semester = semester.trim(),
            status = ClassroomStatus.ACTIVE,
            createdAt = LocalDateTime.now()
        )
        return repository.createClassroom(classroom)
    }
}

class UpdateClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository
) {
    suspend operator fun invoke(classroom: Classroom): Result<Classroom> {
        if (classroom.name.isBlank()) return Result.failure(IllegalArgumentException("Tên lớp không được trống"))
        return repository.updateClassroom(classroom)
    }
}

class GetLecturerClassroomsUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(): List<Classroom> {
        val user = authRepository.getCurrentUser() ?: return emptyList()
        return repository.getClassroomsForLecturer(user.id)
    }
}

class GetStudentClassroomsUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(): List<Classroom> {
        val user = authRepository.getCurrentUser() ?: return emptyList()
        return repository.getClassroomsForStudent(user.id)
    }
}

class JoinClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(joinCode: String): Result<ClassMembership> {
        val code = joinCode.trim().uppercase()
        if (code.isBlank()) return Result.failure(IllegalArgumentException("Mã tham gia không hợp lệ"))

        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))

        if (user.role != UserRole.STUDENT)
            return Result.failure(IllegalArgumentException("Chỉ sinh viên mới có thể tham gia lớp học"))

        return repository.joinClassroom(code, user.id)
    }
}

class GetClassroomStudentsUseCase @Inject constructor(
    private val repository: ClassroomRepository
) {
    suspend operator fun invoke(classroomId: String): List<User> =
        repository.getStudentsInClassroom(classroomId)
}

class RegenerateJoinCodeUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String): Result<String> {
        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))
        val classroom = repository.getClassroomById(classroomId)
            ?: return Result.failure(IllegalArgumentException("Không tìm thấy lớp học"))
        if (classroom.lecturerId != user.id)
            return Result.failure(IllegalArgumentException("Bạn không có quyền thay đổi lớp học này"))
        return repository.regenerateJoinCode(classroomId)
    }
}

class ArchiveClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String): Result<Unit> {
        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))
        val classroom = repository.getClassroomById(classroomId)
            ?: return Result.failure(IllegalArgumentException("Không tìm thấy lớp học"))
        if (classroom.lecturerId != user.id)
            return Result.failure(IllegalArgumentException("Bạn không có quyền lưu trữ lớp học này"))
        return repository.archiveClassroom(classroomId)
    }
}

class GetClassroomByIdUseCase @Inject constructor(
    private val repository: ClassroomRepository
) {
    suspend operator fun invoke(classroomId: String): Classroom? =
        repository.getClassroomById(classroomId)
}
