package com.uigrade.ai.domain.usecase

import com.uigrade.ai.domain.model.ClassMembership
import com.uigrade.ai.domain.model.Classroom
import com.uigrade.ai.domain.model.ClassroomStatus
import com.uigrade.ai.domain.model.JoinRequest
import com.uigrade.ai.domain.model.User
import com.uigrade.ai.domain.model.UserRole
import com.uigrade.ai.domain.repository.AuthRepository
import com.uigrade.ai.domain.repository.ClassroomRepository
import java.time.LocalDateTime
import java.util.UUID
import javax.inject.Inject

class CreateClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(
        name: String,
        courseCode: String,
        description: String,
        semester: String,
        courseName: String = "",
        academicYear: String = "",
        schedule: String = "",
        room: String = ""
    ): Result<Classroom> {
        if (name.isBlank()) return Result.failure(IllegalArgumentException("Tên lớp không được trống"))
        if (courseCode.isBlank()) return Result.failure(IllegalArgumentException("Mã học phần không được trống"))
        if (semester.isBlank()) return Result.failure(IllegalArgumentException("Học kỳ không được trống"))

        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))
        if (user.role != UserRole.LECTURER) {
            return Result.failure(IllegalArgumentException("Chỉ giảng viên mới có thể tạo lớp học"))
        }

        val classroom = Classroom(
            id = UUID.randomUUID().toString(),
            name = name.trim(),
            courseCode = courseCode.trim().uppercase(),
            description = description.trim(),
            lecturerId = user.id,
            lecturerName = user.name,
            joinCode = "", // Generated by repository
            semester = semester.trim(),
            status = ClassroomStatus.ACTIVE,
            createdAt = LocalDateTime.now(),
            courseName = courseName.trim(),
            academicYear = academicYear.trim(),
            schedule = schedule.trim(),
            room = room.trim()
        )
        return repository.createClassroom(classroom)
    }
}

class UpdateClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroom: Classroom): Result<Classroom> {
        if (classroom.name.isBlank()) return Result.failure(IllegalArgumentException("Tên lớp không được trống"))
        if (classroom.courseCode.isBlank()) return Result.failure(IllegalArgumentException("Mã học phần không được trống"))
        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))
        val existing = repository.getClassroomById(classroom.id)
            ?: return Result.failure(IllegalArgumentException("Không tìm thấy lớp học"))
        if (user.role != UserRole.LECTURER || existing.lecturerId != user.id) {
            return Result.failure(IllegalArgumentException("Bạn không có quyền chỉnh sửa lớp học này"))
        }
        return repository.updateClassroom(
            classroom.copy(
                lecturerId = existing.lecturerId,
                lecturerName = existing.lecturerName,
                joinCode = existing.joinCode,
                createdAt = existing.createdAt,
                status = existing.status,
                joinEnabled = existing.joinEnabled
            )
        )
    }
}

class GetLecturerClassroomsUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(): List<Classroom> {
        val user = authRepository.getCurrentUser() ?: return emptyList()
        return repository.getClassroomsForLecturer(user.id)
    }
}

class GetStudentClassroomsUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(): List<Classroom> {
        val user = authRepository.getCurrentUser() ?: return emptyList()
        return repository.getClassroomsForStudent(user.id)
    }
}

class JoinClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(joinCode: String): Result<ClassMembership> {
        val code = joinCode.trim().uppercase()
        if (code.isBlank()) return Result.failure(IllegalArgumentException("Mã tham gia không hợp lệ"))

        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))

        if (user.role != UserRole.STUDENT)
            return Result.failure(IllegalArgumentException("Chỉ sinh viên mới có thể tham gia lớp học"))

        return repository.joinClassroom(code, user.id)
    }
}

class GetClassroomStudentsUseCase @Inject constructor(
    private val repository: ClassroomRepository
) {
    suspend operator fun invoke(classroomId: String): List<User> =
        repository.getStudentsInClassroom(classroomId)
}

class RegenerateJoinCodeUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String): Result<String> {
        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))
        val classroom = repository.getClassroomById(classroomId)
            ?: return Result.failure(IllegalArgumentException("Không tìm thấy lớp học"))
        if (classroom.lecturerId != user.id)
            return Result.failure(IllegalArgumentException("Bạn không có quyền thay đổi lớp học này"))
        return repository.regenerateJoinCode(classroomId)
    }
}

class ArchiveClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String): Result<Unit> {
        val user = authRepository.getCurrentUser()
            ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))
        val classroom = repository.getClassroomById(classroomId)
            ?: return Result.failure(IllegalArgumentException("Không tìm thấy lớp học"))
        if (classroom.lecturerId != user.id)
            return Result.failure(IllegalArgumentException("Bạn không có quyền lưu trữ lớp học này"))
        return repository.archiveClassroom(classroomId)
    }
}

class GetClassroomByIdUseCase @Inject constructor(
    private val repository: ClassroomRepository
) {
    suspend operator fun invoke(classroomId: String): Classroom? =
        repository.getClassroomById(classroomId)
}

class RestoreClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String): Result<Unit> =
        requireOwner(classroomId, repository, authRepository).fold(
            onSuccess = { repository.restoreClassroom(classroomId) },
            onFailure = { Result.failure(it) }
        )
}

class DeleteClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String): Result<Unit> =
        requireOwner(classroomId, repository, authRepository).fold(
            onSuccess = { repository.deleteClassroom(classroomId) },
            onFailure = { Result.failure(it) }
        )
}

class SetClassroomJoinEnabledUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String, enabled: Boolean): Result<Classroom> =
        requireOwner(classroomId, repository, authRepository).fold(
            onSuccess = { repository.setJoinEnabled(classroomId, enabled) },
            onFailure = { Result.failure(it) }
        )
}

class RemoveStudentFromClassroomUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String, studentId: String): Result<Unit> =
        requireOwner(classroomId, repository, authRepository).fold(
            onSuccess = { repository.removeStudent(classroomId, studentId) },
            onFailure = { Result.failure(it) }
        )
}

class GetJoinRequestsUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String): Result<List<JoinRequest>> =
        requireOwner(classroomId, repository, authRepository).mapCatching {
            repository.getJoinRequests(classroomId)
        }
}

class RespondToJoinRequestUseCase @Inject constructor(
    private val repository: ClassroomRepository,
    private val authRepository: AuthRepository
) {
    suspend operator fun invoke(classroomId: String, requestId: String, approve: Boolean): Result<JoinRequest> =
        requireOwner(classroomId, repository, authRepository).fold(
            onSuccess = { repository.respondToJoinRequest(requestId, approve) },
            onFailure = { Result.failure(it) }
        )
}

private suspend fun requireOwner(
    classroomId: String,
    repository: ClassroomRepository,
    authRepository: AuthRepository
): Result<Classroom> {
    val user = authRepository.getCurrentUser()
        ?: return Result.failure(IllegalArgumentException("Bạn chưa đăng nhập"))
    if (user.role != UserRole.LECTURER) {
        return Result.failure(IllegalArgumentException("Chỉ giảng viên mới có quyền thực hiện thao tác này"))
    }
    val classroom = repository.getClassroomById(classroomId)
        ?: return Result.failure(IllegalArgumentException("Không tìm thấy lớp học"))
    if (classroom.lecturerId != user.id) {
        return Result.failure(IllegalArgumentException("Bạn không có quyền thay đổi lớp học này"))
    }
    return Result.success(classroom)
}
